// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLog.Data.DataAccess;

#nullable disable

namespace MyLog.Data.DataAccess.Migrations
{
    [DbContext(typeof(MyLogContext))]
    [Migration("20250115081520_20250115091500_AutoMig")]
    partial class _20250115091500_AutoMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyLog.Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("MyLog.Data.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoNr")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("CargoPayerId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<int?>("PickUpId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoPayerId");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("PickUpId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("MyLog.Data.Models.Movement", b =>
                {
                    b.HasOne("MyLog.Data.Models.Address", "CargoPayer")
                        .WithMany()
                        .HasForeignKey("CargoPayerId");

                    b.HasOne("MyLog.Data.Models.Address", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId");

                    b.HasOne("MyLog.Data.Models.Address", "PickUp")
                        .WithMany()
                        .HasForeignKey("PickUpId");

                    b.Navigation("CargoPayer");

                    b.Navigation("Delivery");

                    b.Navigation("PickUp");
                });
#pragma warning restore 612, 618
        }
    }
}
