@url = https://localhost:7065

GET {{url}}/openapi/v1.json
Accept: application/json

###

GET {{url}}/scalar/v1
Accept: application/json

###

GET {{url}}/movements/5
Accept: application/json

###

POST {{url}}/auth/register
Content-Type: application/json
{
    "username": "bob",
    "password": "123Bobby!",
    "email": "bob@example.com"
}
###

POST {{url}}/auth/login
Content-Type: application/json
{
    "username": "bob",
    "password": "123Bobby!",
    "email": "bob@example.com"
}

###

POST {{url}}/auth/login
Content-Type: application/json
{
    "username": "alice",
    "password": "123Admin!",
    "email": "alice@bob.com"
}

###

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjhiNjMwOWFiLTliZGItNGVlMy1hNWEwLTA3MWNlZDIwM2JkMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhbGljZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFsaWNlQGJvYi5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzM3Mjg1NzYzLCJpc3MiOiJLaWVzc2xpbmctU3BlZGl0aW9uLmRlIiwiYXVkIjoiTXlMb2cuS2llc3NsaW5nLVNwZWRpdGlvbi5kZSJ9.c01SM2xWaMIEiOo2xGDfjOEi65c5lVHRhWyF_Rq8dO4

GET {{url}}/auth/userinfo
Authorization: Bearer {{token}}

###

DELETE {{url}}/movements/1
Authorization: Bearer {{token}}

###


GET {{url}}/movementbyuser/bob
Authorization: Bearer {{token}}

###
